const Conversation = require('../models/Conversation'); const { TutorActionLog } = require('../models/LearningRecords'); const templates = require('../prompts/templates'); const ai = require('./ai.service'); const { getState, updateFromTutor } = require('./learning.service'); const AppError = require('../utils/AppError'); const env = require('../config/env');
const gated = new Set(['diagnose', 'hint', 'checkpoint', 'mini-practice', 'explain-back', 'mastery-validate']);
async function respond({ user, conversationId, message, strictness, traceId }) {
  const conversation = await Conversation.findOne({ _id: conversationId, userId: user._id }); if (!conversation) throw new AppError('Conversation not found', 404);
  const state = await getState(user._id);
  const tutorState = { masteryProgress: state.masteryProgress, confidenceLevel: state.confidenceLevel, knownConcepts: state.knownConcepts.slice(-5).map(item => ({ name: item.name, score: item.score })), weakConcepts: state.weakConcepts.slice(-5).map(item => ({ name: item.name, score: item.score })), misconceptions: state.misconceptions.slice(-4).map(item => ({ concept: item.concept, description: item.description })) };
  const recentConversation = conversation.messages.slice(-6).map(item => ({ role: item.role, content: item.content.slice(0, 600), checkpointQuestion: item.metadata?.checkpointQuestion }));
  let output;
  try { output = await ai.structured({ ...templates.tutor({ message, state: tutorState, strictness: strictness || user.learningPreferences.strictness, conversation: recentConversation }), temperature: 0.2, maxTokens: env.NVIDIA_TUTOR_MAX_TOKENS, retries: 0, timeoutMs: 25000, traceId }); } catch (error) { if (error.statusCode !== 504) throw error; const checkpoint = recentConversation.slice().reverse().find(item => item.checkpointQuestion)?.checkpointQuestion; output = { mode: 'hint', message: `The AI tutor is taking longer than expected, so let’s keep moving with a focused hint: ${checkpoint || 'What is the first small step you would take to solve this?'}`, checkpointQuestion: checkpoint || 'What is one idea you already understand about this topic?', expectedAction: 'answer_short', concepts: [], misconceptions: [], masteryUpdate: { scoreDelta: 0, confidenceDelta: 0 }, allowFinalAnswer: false, answerEvaluation: { status: 'not-applicable', feedback: '', nextQuestion: checkpoint || '' } }; }
  const answerEvaluation = output.answerEvaluation;
  if (answerEvaluation?.status === 'correct') output.message = `✓ Correct. ${answerEvaluation.feedback}${answerEvaluation.nextQuestion ? `\n\nNext question: ${answerEvaluation.nextQuestion}` : ''}`;
  if (answerEvaluation?.status === 'needs-work') output.message = `↻ Not quite yet. ${answerEvaluation.feedback}${answerEvaluation.nextQuestion ? `\n\nTry this: ${answerEvaluation.nextQuestion}` : ''}`;
  if (env.STRICT_TUTOR_MODE === 'true' && output.mode === 'final-answer' && state.masteryProgress < 70) { output.mode = 'checkpoint'; output.allowFinalAnswer = false; output.message = 'You are close. Before I reveal the complete solution, show me your current approach in your own words.'; output.expectedAction = 'explain'; }
  conversation.messages.push({ role: 'student', content: message }); conversation.messages.push({ role: 'assistant', content: output.message, metadata: output }); conversation.hintLevel = output.mode === 'hint' ? Math.min(5, conversation.hintLevel + 1) : conversation.hintLevel; await conversation.save();
  const learningState = await updateFromTutor({ userId: user._id, conversationId, output }); await TutorActionLog.create({ userId: user._id, conversationId, actionType: 'tutor_response', submission: message, result: output, traceId });
  return { conversation, response: output, learningState, gated: gated.has(output.mode) };
}
module.exports = { respond };
